export type GENRE =
    | 'Accounting'
    | 'Action'
    | 'Adventure'
    | 'Animation & Modeling'
    | 'Audio Production'
    | 'Casual'
    | 'Design & Illustration'
    | 'Documentary'
    | 'Early Access'
    | 'Education'
    | 'Free to Play'
    | 'Game Development'
    | 'Gore'
    | 'Indie'
    | 'Massively Multiplayer'
    | 'Nudity'
    | 'Photo Editing'
    | 'Racing'
    | 'RPG'
    | 'Sexual Content'
    | 'Simulation'
    | 'Software Training'
    | 'Sports'
    | 'Strategy'
    | 'Tutorial'
    | 'Utilities'
    | 'Video Production'
    | 'Violent'
    | 'Web Publishing';
