export type STEAMSPY_TAG =
    | '1980s'
    | "1990's"
    | '2.5D'
    | '2D'
    | '2D Fighter'
    | '360 Video'
    | '3D'
    | '3D Platformer'
    | '3D Vision'
    | '4 Player Local'
    | '4X'
    | '6DOF'
    | 'Abstract'
    | 'Action'
    | 'Action RPG'
    | 'Action-Adventure'
    | 'Adventure'
    | 'Agriculture'
    | 'Aliens'
    | 'Alternate History'
    | 'America'
    | 'Animation & Modeling'
    | 'Anime'
    | 'Arcade'
    | 'Arena Shooter'
    | 'Assassin'
    | 'Atmospheric'
    | 'Audio Production'
    | 'Base-Building'
    | 'Baseball'
    | 'Basketball'
    | 'Batman'
    | 'Battle Royale'
    | "Beat 'em up"
    | 'Beautiful'
    | 'Benchmark'
    | 'Bikes'
    | 'Blood'
    | 'BMX'
    | 'Board Game'
    | 'Bowling'
    | 'Building'
    | 'Bullet Hell'
    | 'Bullet Time'
    | 'Capitalism'
    | 'Card Game'
    | 'Cartoon'
    | 'Cartoony'
    | 'Casual'
    | 'Cats'
    | 'Character Action Game'
    | 'Character Customization'
    | 'Chess'
    | 'Choices Matter'
    | 'Choose Your Own Adventure'
    | 'Cinematic'
    | 'City Builder'
    | 'Class-Based'
    | 'Classic'
    | 'Clicker'
    | 'Co-op'
    | 'Cold War'
    | 'Colorful'
    | 'Comedy'
    | 'Comic Book'
    | 'Competitive'
    | 'Controller'
    | 'Conversation'
    | 'Crafting'
    | 'Crime'
    | 'CRPG'
    | 'Cult Classic'
    | 'Cute'
    | 'Cyberpunk'
    | 'Cycling'
    | 'Dark'
    | 'Dark Fantasy'
    | 'Dark Humor'
    | 'Dating Sim'
    | 'Demons'
    | 'Design & Illustration'
    | 'Destruction'
    | 'Detective'
    | 'Difficult'
    | 'Dinosaurs'
    | 'Diplomacy'
    | 'Documentary'
    | 'Dog'
    | 'Dragons'
    | 'Drama'
    | 'Driving'
    | 'Dungeon Crawler'
    | 'Dungeons & Dragons'
    | 'Dystopian '
    | 'e-sports'
    | 'Early Access'
    | 'Economy'
    | 'Education'
    | 'Epic'
    | 'Experimental'
    | 'Exploration'
    | 'Faith'
    | 'Family Friendly'
    | 'Fantasy'
    | 'Fast-Paced'
    | 'Female Protagonist'
    | 'Fighting'
    | 'First-Person'
    | 'Fishing'
    | 'Flight'
    | 'FMV'
    | 'Football'
    | 'FPS'
    | 'Free to Play'
    | 'Funny'
    | 'Futuristic'
    | 'Gambling'
    | 'Game Development'
    | 'GameMaker'
    | 'Games Workshop'
    | 'God Game'
    | 'Golf'
    | 'Gore'
    | 'Gothic'
    | 'Grand Strategy'
    | 'Great Soundtrack'
    | 'Grid-Based Movement'
    | 'Gun Customization'
    | 'Hack and Slash'
    | 'Hacking'
    | 'Hand-drawn'
    | 'Heist'
    | 'Hex Grid'
    | 'Hidden Object'
    | 'Historical'
    | 'Hockey'
    | 'Horror'
    | 'Horses'
    | 'Hunting'
    | 'Illuminati'
    | 'Indie'
    | 'Intentionally Awkward Controls'
    | 'Interactive Fiction'
    | 'Inventory Management'
    | 'Investigation'
    | 'Isometric'
    | 'JRPG'
    | 'Kickstarter'
    | 'Lara Croft'
    | 'LEGO'
    | 'Lemmings'
    | 'Level Editor'
    | 'Linear'
    | 'Local Co-Op'
    | 'Local Multiplayer'
    | 'Logic'
    | 'Loot'
    | 'Lovecraftian'
    | 'Magic'
    | 'Management'
    | 'Mars'
    | 'Martial Arts'
    | 'Massively Multiplayer'
    | 'Masterpiece'
    | 'Match 3'
    | 'Mature'
    | 'Mechs'
    | 'Medieval'
    | 'Memes'
    | 'Metroidvania'
    | 'Military'
    | 'Mini Golf'
    | 'Minimalist'
    | 'Mining'
    | 'MMORPG'
    | 'MOBA'
    | 'Mod'
    | 'Moddable'
    | 'Motocross'
    | 'Motorbike'
    | 'Mouse only'
    | 'Movie'
    | 'Multiplayer'
    | 'Multiple Endings'
    | 'Music'
    | 'Music-Based Procedural Generation'
    | 'Mystery'
    | 'Mystery Dungeon'
    | 'Mythology'
    | 'Narration'
    | 'Naval'
    | 'Ninja'
    | 'Noir'
    | 'Nonlinear'
    | 'NSFW'
    | 'Nudity'
    | 'Offroad'
    | 'Old School'
    | 'On-Rails Shooter'
    | 'Online Co-Op'
    | 'Open World'
    | 'Otome'
    | 'Parkour'
    | 'Parody '
    | 'Party-Based RPG'
    | 'Perma Death'
    | 'Philisophical'
    | 'Photo Editing'
    | 'Physics'
    | 'Pinball'
    | 'Pirates'
    | 'Pixel Graphics'
    | 'Platformer'
    | 'Point & Click'
    | 'Political'
    | 'Politics'
    | 'Pool'
    | 'Post-apocalyptic'
    | 'Procedural Generation'
    | 'Programming'
    | 'Psychedelic'
    | 'Psychological'
    | 'Psychological Horror'
    | 'Puzzle'
    | 'Puzzle-Platformer'
    | 'PvP'
    | 'Quick-Time Events'
    | 'Racing'
    | 'Real Time Tactics'
    | 'Real-Time'
    | 'Real-Time with Pause'
    | 'Realistic'
    | 'Relaxing'
    | 'Remake'
    | 'Replay Value'
    | 'Resource Management'
    | 'Retro'
    | 'Rhythm'
    | 'Robots'
    | 'Rogue-like'
    | 'Rogue-lite'
    | 'Romance'
    | 'Rome'
    | 'RPG'
    | 'RPGMaker'
    | 'RTS'
    | 'Runner'
    | 'Sailing'
    | 'Sandbox'
    | 'Satire'
    | 'Sci-fi'
    | 'Science'
    | 'Score Attack'
    | 'Sexual Content'
    | "Shoot 'Em Up"
    | 'Shooter'
    | 'Short'
    | 'Side Scroller'
    | 'Simulation'
    | 'Singleplayer'
    | 'Skateboarding'
    | 'Skating'
    | 'Sniper'
    | 'Snow'
    | 'Snowboarding'
    | 'Soccer'
    | 'Software'
    | 'Software Training'
    | 'Sokoban'
    | 'Souls-like'
    | 'Space'
    | 'Space Sim'
    | 'Spectacle fighter'
    | 'Spelling'
    | 'Split Screen'
    | 'Sports'
    | 'Star Wars'
    | 'Stealth'
    | 'Steampunk'
    | 'Story Rich'
    | 'Strategy'
    | 'Strategy RPG'
    | 'Stylized'
    | 'Submarine'
    | 'Superhero'
    | 'Supernatural'
    | 'Surreal'
    | 'Survival'
    | 'Survival Horror'
    | 'Swordplay'
    | 'Tactical'
    | 'Tactical RPG'
    | 'Tanks'
    | 'Team-Based'
    | 'Tennis'
    | 'Text-Based'
    | 'Third Person'
    | 'Third-Person Shooter'
    | 'Thriller'
    | 'Time Attack'
    | 'Time Management'
    | 'Time Manipulation'
    | 'Time Travel'
    | 'Top-Down'
    | 'Top-Down Shooter'
    | 'Touch-Friendly'
    | 'Tower Defense'
    | 'Trading'
    | 'Trading Card Game'
    | 'Trains'
    | 'Turn-Based'
    | 'Turn-Based Combat'
    | 'Turn-Based Strategy'
    | 'Turn-Based Tactics'
    | 'Twin Stick Shooter'
    | 'Typing'
    | 'Underwater'
    | 'Utilities'
    | 'Vampire'
    | 'Video Production'
    | 'Villain Protagonist'
    | 'Violent'
    | 'Visual Novel'
    | 'Voice Control'
    | 'Voxel'
    | 'VR'
    | 'VR Only'
    | 'Walking Simulator'
    | 'War'
    | 'Wargame'
    | 'Warhammer 40K'
    | 'Web Publishing'
    | 'Werewolves'
    | 'Western'
    | 'Word Game'
    | 'World War I'
    | 'World War II'
    | 'Wrestling'
    | 'Zombies';
